title: SudoDEM
description: Discrete Element Code for Non-spherical Particles
show_downloads: false
google_analytics: UA-144989471-1
theme: jekyll-theme-modernist
show_publications: false


# Reading Files
include:

exclude:
  - index0
  - LICENSE
  - Rakefile
  - README
  - tmp


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
